markdown: redcarpet
pygments: true
permalink: /:categories/:year/:month/:day/:title.html
url: http://summerdaysinbloom.github.io/techteamshare
# url: http://localhost:4000
# Description and information
author: Aimee
title: Boilerplates:title
name: Boilerplates:name
description: boilerplates